# Generated by Django 3.1.3 on 2020-11-26 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_Station', models.CharField(max_length=120)),
                ('quantityBike', models.IntegerField()),
                ('quantityElecBike', models.IntegerField()),
                ('quantityElecMoto', models.IntegerField()),
                ('totalVehicle', models.IntegerField()),
                ('remainVehicle', models.IntegerField()),
                ('longitude', models.CharField(max_length=120)),
                ('latitude', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_User', models.CharField(max_length=120)),
                ('username', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Rent_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('timeDepart', models.TimeField(auto_now_add=True)),
                ('timeArrive', models.TimeField(auto_now_add=True)),
                ('stationDepart', models.CharField(max_length=120)),
                ('stationArrive', models.CharField(max_length=120)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.user')),
            ],
        ),
    ]
