# Generated by Django 3.1.3 on 2020-12-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20201202_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='quantityBike',
        ),
        migrations.RemoveField(
            model_name='station',
            name='quantityElecBike',
        ),
        migrations.RemoveField(
            model_name='station',
            name='quantityElecMoto',
        ),
        migrations.RemoveField(
            model_name='station',
            name='remainVehicle',
        ),
        migrations.RemoveField(
            model_name='station',
            name='totalVehicle',
        ),
        migrations.AddField(
            model_name='station',
            name='address',
            field=models.CharField(default='', max_length=120),
        ),
    ]
