# Generated by Django 3.1.3 on 2020-12-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20201203_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='latitude',
            field=models.FloatField(max_length=120),
        ),
        migrations.AlterField(
            model_name='station',
            name='longitude',
            field=models.FloatField(max_length=120),
        ),
    ]
