# Generated by Django 3.1.3 on 2020-12-03 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_auto_20201203_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='Belong_Station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listBike', to='locations.station'),
        ),
    ]
