# Generated by Django 3.1.3 on 2020-12-11 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_auto_20201206_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elecbike',
            name='Belong_Station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listElecBike', to='locations.station'),
        ),
        migrations.AlterField(
            model_name='elecmoto',
            name='Belong_Station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listElecMoto', to='locations.station'),
        ),
    ]
