# Generated by Django 3.1.3 on 2020-12-14 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0013_auto_20201213_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent_detail',
            name='date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='history',
        ),
        migrations.AlterField(
            model_name='rent_detail',
            name='timeArrive',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rent_detail',
            name='timeDepart',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rent_detail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='locations.user'),
        ),
    ]
