# Generated by Django 3.1.3 on 2020-12-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0014_auto_20201214_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tempsDepart',
            field=models.DateTimeField(null=True),
        ),
    ]
