# Generated by Django 3.1.3 on 2020-12-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0016_user_stationarrive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent_detail',
            name='timeArrive',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='rent_detail',
            name='timeDepart',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='tempsDepart',
            field=models.CharField(default='', max_length=120),
        ),
    ]
