# Generated by Django 3.1.3 on 2020-12-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0017_auto_20201214_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent_detail',
            name='stationArrive',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='rent_detail',
            name='stationDepart',
            field=models.CharField(default='', max_length=120),
        ),
    ]
