# Generated by Django 3.1.3 on 2020-12-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0018_auto_20201214_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent_detail',
            name='cost',
            field=models.IntegerField(),
        ),
    ]
