# Generated by Django 3.1.3 on 2020-12-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0019_auto_20201214_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isGiveBack',
            field=models.CharField(default='', max_length=120),
        ),
    ]
