# Generated by Django 3.1.3 on 2020-12-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0019_auto_20201214_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('value', models.FloatField()),
                ('point', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='rewardList',
            field=models.ManyToManyField(to='locations.Award'),
        ),
    ]
