# Generated by Django 3.1.3 on 2020-12-15 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0019_auto_20201214_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent_detail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='locations.user'),
        ),
    ]
