# Generated by Django 3.1.3 on 2020-12-15 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0021_auto_20201215_1240'),
        ('locations', '0020_user_isgiveback'),
    ]

    operations = [
    ]
