# Generated by Django 3.1.3 on 2020-12-15 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0020_auto_20201215_2058'),
        ('locations', '0022_merge_20201215_1021'),
    ]

    operations = [
    ]
