# Generated by Django 3.1.3 on 2020-12-15 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0023_merge_20201215_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rent_detail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='locations.user'),
        ),
    ]
