# Generated by Django 3.1.3 on 2021-01-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0024_auto_20201215_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tempCost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='tempPoint',
            field=models.IntegerField(default=0),
        ),
    ]
